databases:
  - name: cobranca-db
    databaseName: cobranca
    user: cobranca

services:
  - type: web
    name: nutrivera-cobranca
    runtime: node
    buildCommand: npm install
    startCommand: node server.js
    envVars:
      - key: PORT
        value: 3001
      - key: DATABASE_URL
        fromDatabase:
          name: cobranca-db
          property: connectionString
      - key: EVOLUTION_URL
        value: https://evolutionapi.vps7269.panel.icontainer.cloud
      - key: EVOLUTION_APIKEY
        value: ztDtdXQmBijCrjwNSWjXepr477a6w6rj
      - key: DEFAULT_SENDERS
        value: A1,A2,A3
      - key: APP_URL
        value: https://nutrivera-cobranca.onrender.com
